# Generated by Django 5.0.6 on 2024-05-24 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_imagesetting_alter_generalsetting_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagesetting',
            old_name='image',
            new_name='file',
        ),
    ]
