# Generated by Django 5.0.6 on 2024-05-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_imagesetting_alter_generalsetting_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsetting',
            name='description',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='Description'),
        ),
    ]
