# Generated by Django 5.0.6 on 2024-05-23 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_generalsetting_parameter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagesetting',
            old_name='updated_date',
            new_name='updatedd_date',
        ),
        migrations.RemoveField(
            model_name='generalsetting',
            name='updatedd_date',
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='updatedd_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated Date'),
        ),
    ]
