# Generated by Django 5.0.6 on 2024-05-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_updated_date_imagesetting_updatedd_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalsetting',
            name='updatedd_date',
        ),
        migrations.AlterField(
            model_name='generalsetting',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated Date'),
        ),
    ]
